version: 2.1

executors:
  php:
    parameters:
      php_version: { type: string, default: "7.2" }
    docker:
    - image: thecodingmachine/php:<< parameters.php_version >>-v2-apache
    environment:
      PHP_EXTENSIONS: gd intl pdo_mysql xsl zip soap bcmath opcache mcrypt
      PHP_INI_MEMORY_LIMIT: "-1"

commands:
  configure_php:
    steps:
      - run:
          name: Configure PHP
          command: php /usr/local/bin/generate_conf.php | sudo su -c "tee /usr/local/etc/php/conf.d/generated_conf.ini" > /dev/null

jobs:
  build:
    parameters:
      php_version: { type: string }
      magento_version: { type: string }
      magento_edition: { type: string, default: community }
    executor:
      name: php
      php_version: << parameters.php_version >>
    steps:
    - configure_php
    - checkout:
        path: repo
    - restore_cache:
        keys:
        - v3-dependencies-<< parameters.magento_version >>-<< parameters.magento_edition >>-<< parameters.php_version >>-{{ checksum "repo/composer.json" }}
        - v3-dependencies-<< parameters.magento_version >>-<< parameters.magento_edition >>-<< parameters.php_version >>
        - v3-dependencies-<< parameters.magento_version >>
    - run:
        name: Install Magento
        command: |
            MAGE_REPO="https://repo.magento.com/"
            if [ -z "$COMPOSER_AUTH" ]; then
              MAGE_REPO="https://repo-magento-mirror.fooman.co.nz/"
            fi
            echo $MAGE_REPO
            composer config -g repositories.magento composer ${MAGE_REPO}
            composer create-project --no-install magento/project-<< parameters.magento_edition >>-edition:<< parameters.magento_version >> magento
    - run:
        name: Install App Search module
        command: |
          cd magento
          composer config --unset repo.0
          composer config repositories.app-search '{"type": "path", "url": "../repo"}'
          composer config "minimum-stability" dev
          composer require elastic/app-search-magento --no-update
          composer install
    - run:
        name: Enable Magento modules
        command: cd magento && bin/magento module:enable --all
    - save_cache:
        paths:
        - ~/.composer
        key: v3-dependencies-<< parameters.magento_version >>-<< parameters.magento_edition >>-<< parameters.php_version >>-{{ checksum "repo/composer.json" }}
    - persist_to_workspace:
        root: .
        paths:
        - .

  code-quality:
    executor: php
    working_directory: ~/project/repo
    steps:
    - configure_php
    - attach_workspace:
        at: ~/project
    - restore_cache:
        keys:
        - v3-dependencies-
    - restore_cache:
        keys:
        - v3-qa-dependencies-{{ checksum "composer.json" }}
    - run:
        name: Install dev dependencies
        command: composer install
    - run:
        name: Check coding quality against PSR12 rules
        command: vendor/bin/phpcs . --extensions=php --ignore=vendor/*,.git/*,dev
    - run:
        name: Check coding quality using phpmd
        command: vendor/bin/phpmd . text cleancode,codesize,controversial,design,naming,unusedcode --exclude vendor,.git --suffixes php
    - save_cache:
        paths:
        - ~/.composer
        key: v3-qa-dependencies-{{ checksum "composer.json" }}

  compile:
    parameters:
      php_version: { type: string }
    executor:
      name: php
      php_version: << parameters.php_version >>
    working_directory: ~/project/magento
    steps:
    - configure_php
    - attach_workspace:
        at: ~/project
    - run:
        name: Compile Magento DI
        command: bin/magento setup:di:compile

  tests:
    parameters:
      php_version: { type: string }
      testsuite: { type: string }
    executor:
      name: php
      php_version: << parameters.php_version >>
    working_directory: ~/project/magento
    steps:
    - configure_php
    - attach_workspace:
        at: ~/project
    - run:
        name: Copying test suite config.
        command: cp vendor/elastic/app-search-magento/dev/tests/<< parameters.testsuite >>/phpunit.xml.dist dev/tests/<< parameters.testsuite >>/
    - run:
        name: Running test suite (<< parameters.testsuite >>)
        command: vendor/bin/phpunit -c dev/tests/<< parameters.testsuite >>/phpunit.xml.dist

workflows:
  php-7.2-mage-2.3:
    jobs:
    - build:
        name: build-php-7.2-mage-2.3
        php_version: "7.2"
        magento_version: 2.3.1
    - compile:
        name: compile-php-7.2-mage-2.3
        php_version: "7.2"
        requires:
        - build-php-7.2-mage-2.3
    - tests:
        name: unit-test-php-7.2-mage-2.3
        php_version: "7.2"
        testsuite: unit
        requires:
        - build-php-7.2-mage-2.3
    - code-quality:
        requires:
        - build-php-7.2-mage-2.3
  php-7.1-mage-2.3:
    jobs:
    - build:
        name: build-php-7.1-mage-2.3
        php_version: "7.1"
        magento_version: 2.3.1
    - compile:
        name: compile-php-7.1-mage-2.3
        php_version: "7.1"
        requires:
        - build-php-7.1-mage-2.3
    - tests:
        name: unit-test-php-7.1-mage-2.3
        php_version: "7.1"
        testsuite: unit
        requires:
        - build-php-7.1-mage-2.3
  php-7.1-mage-2.2:
    jobs:
    - build:
        name: build-php-7.1-mage-2.2
        php_version: "7.1"
        magento_version: ^2.2
    - compile:
        name: compile-php-7.1-mage-2.2
        php_version: "7.1"
        requires:
        - build-php-7.1-mage-2.2
    - tests:
        name: unit-test-php-7.1-mage-2.2
        php_version: "7.1"
        testsuite: unit
        requires:
        - build-php-7.1-mage-2.2
